#ifndef BLACKBOX_H
#define BLACKBOX_H

#include <stdbool.h>
#include <stdint.h>

enum blackbox_counter {
    BLACKBOX_COUNTER_BOOT = 0,
    BLACKBOX_COUNTER_BLE_CONNECT,
    BLACKBOX_COUNTER_BLE_CONNECT_ERROR,
    BLACKBOX_COUNTER_BLE_DISCONNECT,
    BLACKBOX_COUNTER_LINK_SETUP_ATTEMPT,
    BLACKBOX_COUNTER_LINK_SETUP_ERROR,
    BLACKBOX_COUNTER_AUDIO_FRAME,
    BLACKBOX_COUNTER_AUDIO_QUEUE_FULL,
    BLACKBOX_COUNTER_AUDIO_TX_SLOT_TIMEOUT,
    BLACKBOX_COUNTER_AUDIO_NOTIFY_ACCEPTED,
    BLACKBOX_COUNTER_AUDIO_NOTIFY_COMPLETED,
    BLACKBOX_COUNTER_AUDIO_NOTIFY_ENOMEM,
    BLACKBOX_COUNTER_AUDIO_NOTIFY_EAGAIN,
    BLACKBOX_COUNTER_AUDIO_NOTIFY_EBUSY,
    BLACKBOX_COUNTER_AUDIO_NOTIFY_ENOTCONN,
    BLACKBOX_COUNTER_AUDIO_NOTIFY_OTHER_ERROR,
    BLACKBOX_COUNTER_STORAGE_ACCEPTED,
    BLACKBOX_COUNTER_STORAGE_REJECTED,
    BLACKBOX_COUNTER_FRAME_RETAINED,
    BLACKBOX_COUNTER_FRAME_DROPPED,
    BLACKBOX_COUNTER_MIC_BUFFER,
    BLACKBOX_COUNTER_MIC_READ_ERROR,
    BLACKBOX_COUNTER_VOICE_GATE_OPEN,
    BLACKBOX_COUNTER_VOICE_GATE_CLOSE,
    BLACKBOX_COUNTER_AAD_WAKE,
    BLACKBOX_COUNTER_AAD_SLEEP,
    BLACKBOX_COUNTER_SD_WRITE_QUEUED,
    BLACKBOX_COUNTER_SD_WRITE_REJECTED,
    BLACKBOX_COUNTER_SD_HEALTH_DEGRADED,
    BLACKBOX_COUNTER_SD_HEALTH_TERMINAL,
    BLACKBOX_COUNTER_SYNC_INFO,
    BLACKBOX_COUNTER_SYNC_READ,
    BLACKBOX_COUNTER_SYNC_ADVANCE,
    BLACKBOX_COUNTER_SYNC_STOP,
    BLACKBOX_COUNTER_SYNC_DONE,
    BLACKBOX_COUNTER_SYNC_ERROR,
    BLACKBOX_COUNTER_SYNC_BYTES,
    BLACKBOX_COUNTER_DIAGNOSTIC_REQUEST,
    BLACKBOX_COUNTER_DIAGNOSTIC_BUSY,
    BLACKBOX_COUNTER_COUNT,
};

enum blackbox_event {
    BLACKBOX_EVENT_BOOT = 1,
    BLACKBOX_EVENT_BLE_CONNECTED,
    BLACKBOX_EVENT_BLE_CONNECT_ERROR,
    BLACKBOX_EVENT_BLE_DISCONNECTED,
    BLACKBOX_EVENT_LINK_PARAMS,
    BLACKBOX_EVENT_PHY,
    BLACKBOX_EVENT_DATA_LENGTH,
    BLACKBOX_EVENT_MTU,
    BLACKBOX_EVENT_LINK_SETUP_ERROR,
    BLACKBOX_EVENT_AUDIO_QUEUE_FULL,
    BLACKBOX_EVENT_AUDIO_TX_TIMEOUT,
    BLACKBOX_EVENT_AUDIO_NOTIFY_ERROR,
    BLACKBOX_EVENT_STORAGE_REJECTED,
    BLACKBOX_EVENT_FRAME_RETAINED,
    BLACKBOX_EVENT_FRAME_DROPPED,
    BLACKBOX_EVENT_MIC_READ_ERROR,
    BLACKBOX_EVENT_VOICE_GATE_OPEN,
    BLACKBOX_EVENT_VOICE_GATE_CLOSE,
    BLACKBOX_EVENT_AAD_WAKE,
    BLACKBOX_EVENT_AAD_SLEEP,
    BLACKBOX_EVENT_SD_HEALTH,
    BLACKBOX_EVENT_SYNC_INFO,
    BLACKBOX_EVENT_SYNC_READ,
    BLACKBOX_EVENT_SYNC_ADVANCE,
    BLACKBOX_EVENT_SYNC_STOP,
    BLACKBOX_EVENT_SYNC_DONE,
    BLACKBOX_EVENT_SYNC_ERROR,
    BLACKBOX_EVENT_TRACE_STARTED,
    BLACKBOX_EVENT_TRACE_STOPPED,
    BLACKBOX_EVENT_COUNT,
};

int blackbox_init(uint32_t reset_reason, uint32_t boot_count);
int blackbox_register_service(void);
void blackbox_counter_add(enum blackbox_counter counter, uint32_t amount);
void blackbox_record(enum blackbox_event event, int32_t arg0, int32_t arg1);
void blackbox_record_rate_limited(enum blackbox_event event, int32_t arg0, int32_t arg1, uint32_t min_interval_ms);
void blackbox_set_link_params(uint16_t interval, uint16_t latency, uint16_t timeout);
void blackbox_set_phy(uint8_t tx_phy, uint8_t rx_phy);
void blackbox_set_data_length(uint16_t tx_length, uint16_t rx_length);
void blackbox_set_mtu(uint16_t mtu);
void blackbox_set_battery(uint16_t millivolts, uint8_t percentage, bool charging);
void blackbox_set_sd_state(bool powered, bool ready, uint8_t health);

#endif // BLACKBOX_H
